services:
  - type: web
    name: 2050-token-static
    env: static
    plan: starter
    buildCommand: npm run render-build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
